
# Site settings
title:            Ris Adams
email:            info@risadams.com
description:      The homepage for Ris Adams
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'http://risadams.com/' # The base hostname & protocol for your site
github_username:  risadams
twitter_username: ris_adams

markdown:  kramdown
permalink: pretty
paginate:  12

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:             Ris Adams
    bio:              todo
    gravatar:         https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:            info@risadams.com
    website:          http://aspirethemes.com
    github_username:  risadams
    twitter_username: ris_adams