
# Site settings
title:            Ris Adams
email:            info@risadams.com
description:      The homepage for Ris Adams
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'http://risadams.com/' # The base hostname & protocol for your site
github_username:  risadams
twitter_username: ris_adams
instagram_username: ris.adams
facebook_username: ris.adams.53

markdown:  kramdown
permalink: pretty
paginate:  12
category_dir: topics
category_title_prefix:

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - SECURITY.md
  - SUPPORT.md
  - LICENSE

sass:
  style: compressed

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ris:
    name:             Ris Adams
    email:            contact_bio@risadams.com
    bio:              Professional Developer, Father, Human Rights Advocate, and Founder of the Dire Hope Foundation
    gravatar:         https://en.gravatar.com/userimage/1145971/8444b44eb6432be2ca017f3f63fb6cd8.jpg?2=150
    website:          http://risadams.com
    github_username:  risadams
    twitter_username: ris_adams